# main text of home
name: Circle
bio: Keep taking risks till you find your passion

# twitter summary info
description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpeg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume

url: https://circle.hero666.cn
# your url: http://USERNAME.github.io

# 仓库名
repo: blog

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-113324386-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# 是否使用 gitment 开启评论，categories 为空则不启用
gitment:
  client_id: 4a69a6095513d9f01f07
  client_secret: bd4841122c96cd28fdee9b48271d0cfd05ca1a3d
  categories: [blog, first, second]

# if you don't have any of social below, comment the line
facebook: profile.php?id=100018569020577
twitter: circle_liang
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: rust17
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
# weibo: u/2180398282/home?wvr=5&lf=reg
email: newnash13@gmail.com

authors:
    circle:
        name: circle
        bio: Keep taking risks till you find your passion
        external-image: false
        picture: assets/images/profile.jpeg
        twitter: circle_liang

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 10
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# 表明 markdown 渲染器
markdown: kramdown

# support multiple folder in post
category: origin
category: first
category: second
